In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
url = 'https://www.imdb.com/search/title/?count=100&groups=top_1000&sort=user_rating'

In [3]:
titles = []
ranking = []
years = []
durations = []
votes_numbers = []
scores = []
metascores = []
gross = []

In [4]:
def extract_movies(movies, titles, ranking, years, durations, votes_numbers, scores,
                  metascores, gross):
    for movie in movies:
        header = movie.find('h3', attrs={'class': 'lister-item-header'})
        year = header.find('span', attrs={'lister-item-year text-muted unbold'})
        years.append(year)
        titles.append(header.a.text)
        ranking.append(header.span.text)

        time = movie.find('span', attrs={'class' : 'runtime'})
        durations.append(time.text)

        score = movie.find('div', attrs={'class' : 'inline-block ratings-imdb-rating'})
        scores.append(score.text)

        metascore = movie.find('span', attrs={'class' : 'metascore favorable'})
        if metascore is not None:
            metascores.append(metascore.text)
        else:
            metascores.append(-1)

        votes = movie.findAll('span', attrs={'name' : 'nv'})
        votes_numbers.append(votes[0].text)

        if len(votes) > 1:
            gross.append(votes[1].text)
        else:
            gross.append(-1)

In [5]:
base_link = 'https://www.imdb.com'

In [6]:
while url != '':
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    movies = soup.findAll('div', attrs={'class' : 'lister-item mode-advanced'})
    extract_movies(movies, titles, ranking, years, durations, votes_numbers, scores, metascores, gross)
    link = soup.find('a', attrs={'class' : 'lister-page-next next-page'})
    if link is not None:
        url = base_link + link['href']
    else:
        url = ''
    print(url)

https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&count=100&start=101
https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&count=100&start=201
https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&count=100&start=301
https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&count=100&start=401
https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&count=100&start=501
https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&count=100&start=601
https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&count=100&start=701
https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&count=100&start=801
https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&count=100&start=901

In [7]:
movie_df = pd.DataFrame({'Title': titles, 'Ranking' : ranking, 'Year' : years, 'Time' : durations, 'Votes' : votes_numbers, 'Score' : scores, 'Metascore' : metascores, 'Gross' : gross})

In [8]:
movie_df

,Title,Ranking,Year,Time,Votes,Score,Metascore,Gross
0,Skazani na Shawshank,1.,[(1994)],142 min,"2,658,272",\n\n9.3\n,81,$28.34M
1,Ojciec chrzestny,2.,[(1972)],175 min,"1,842,328",\n\n9.2\n,100,$134.97M
2,Kantara,3.,[(2022)],148 min,"62,300",\n\n9.1\n,-1,-1
3,Mroczny Rycerz,4.,[(2008)],152 min,"2,631,107",\n\n9.0\n,84,$534.86M
4,Władca Pierścieni: Powrót króla,5.,[(2003)],201 min,"1,832,868",\n\n9.0\n,94,$377.85M
...,...,...,...,...,...,...,...,...
995,Sabrina,996.,[(1954)],113 min,"65,578",\n\n7.6\n,72,-1
996,Stąd do wieczności,997.,[(1953)],118 min,"47,411",\n\n7.6\n,85,$30.50M
997,Królewna Śnieżka i siedmiu krasnoludków,998.,[(1937)],83 min,"200,034",\n\n7.6\n,95,$184.93M
998,39 kroków,999.,[(1935)],86 min,"57,488",\n\n7.6\n,93,-1
999,Niewidzialny człowiek,"1,000.",[(1933)],71 min,"36,009",\n\n7.6\n,87,-1